# Generated by Django 4.0.6 on 2022-07-19 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_projects', '0002_rename_desctription_projects_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='image',
            new_name='img',
        ),
    ]
